services:
  db:
    container_name: guild_build_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - my-db:/var/lib/mysql

  api:
    container_name: guild_build_api_dev
    build:
      context: .
      target: pre-build
    depends_on:
      - db
    volumes:
    - ./:/app
      - /app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    command: npm run dev
    env_file: .env

volumes:
  my-db: